/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrainzUp;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author x14102145
 */
public class Badges_animals extends javax.swing.JPanel {

    private ArrayList<Member> current;
    private ArrayList<BadgeInfo> badgez;
    File inFile;
    FileInputStream finStream;
    ObjectInputStream oinStream;
    File outFile;
    FileOutputStream fStream;
    ObjectOutputStream oStream;
    String[] badges;
    String curPlay;

    /**
     * Creates new form Badges_animals
     */
    public Badges_animals() {
        initComponents();
        ArrayList<Member> current = new ArrayList<>();
        ArrayList<BadgeInfo> badgez = new ArrayList<>();
        badges = new String[6];
        curPlay = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBadge1A = new javax.swing.JButton();
        btnBadge2A = new javax.swing.JButton();
        btnBadge3A = new javax.swing.JButton();
        btnBadge4A = new javax.swing.JButton();
        btnBadge5A = new javax.swing.JButton();
        btnBadge6A = new javax.swing.JButton();
        lblBadge1A = new javax.swing.JLabel();
        lblBadge2A = new javax.swing.JLabel();
        lblBadge3A = new javax.swing.JLabel();
        lblBadge6A = new javax.swing.JLabel();
        lblBadge5A = new javax.swing.JLabel();
        lblBadge4A = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        ScreenLabel = new javax.swing.JLabel();
        curPlayer = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        Sound = new javax.swing.JButton();
        jLabelAnimals = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBadge1A.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge1A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge1A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge1A.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnBadge1AComponentShown(evt);
            }
        });
        btnBadge1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge1AActionPerformed(evt);
            }
        });
        add(btnBadge1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 90));

        btnBadge2A.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge2A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge2A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge2A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge2AActionPerformed(evt);
            }
        });
        add(btnBadge2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, 90));

        btnBadge3A.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge3A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge3A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge3AActionPerformed(evt);
            }
        });
        add(btnBadge3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 120, 90));

        btnBadge4A.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge4A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge4A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge4A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge4AActionPerformed(evt);
            }
        });
        add(btnBadge4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, 90));

        btnBadge5A.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge5A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge5A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge5A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge5AActionPerformed(evt);
            }
        });
        add(btnBadge5A, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 120, 90));

        btnBadge6A.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge6A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge6A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge6A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge6AActionPerformed(evt);
            }
        });
        add(btnBadge6A, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 120, 90));

        lblBadge1A.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge1A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge1A.setText("<Locked>");
        lblBadge1A.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 205, 120, 20));

        lblBadge2A.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge2A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge2A.setText("<Locked>");
        lblBadge2A.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 205, 120, 20));

        lblBadge3A.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge3A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge3A.setText("<Locked>");
        lblBadge3A.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 205, 120, 20));

        lblBadge6A.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge6A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge6A.setText("<Locked>");
        lblBadge6A.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge6A, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 325, 120, 20));

        lblBadge5A.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge5A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge5A.setText("<Locked>");
        lblBadge5A.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge5A, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 325, 120, 20));

        lblBadge4A.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge4A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge4A.setText("<Locked>");
        lblBadge4A.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 325, 120, 20));

        Logo.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 40)); // NOI18N
        Logo.setForeground(new java.awt.Color(0, 153, 0));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setText("BrainzUp");
        add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, 40));

        ScreenLabel.setBackground(new java.awt.Color(153, 255, 255));
        ScreenLabel.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        ScreenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScreenLabel.setText("Animals Badges");
        ScreenLabel.setOpaque(true);
        add(ScreenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 230, -1));

        curPlayer.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        curPlayer.setForeground(new java.awt.Color(0, 0, 204));
        curPlayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(curPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        BackBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackBtn.setContentAreaFilled(false);
        BackBtn.setOpaque(true);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 70));

        Sound.setBackground(new java.awt.Color(255, 255, 255));
        Sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpg"))); // NOI18N
        Sound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sound.setContentAreaFilled(false);
        Sound.setOpaque(true);
        Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundActionPerformed(evt);
            }
        });
        add(Sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 70));

        jLabelAnimals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hand_wallpaper.jpg"))); // NOI18N
        add(jLabelAnimals, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBadge1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge1AActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/animals1.jpg");
        if (badges[0].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 1 of the Animals Mix & Match game 1!", "Animals Badge 1", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Animals Mix & Match game to unlock it.", "Animals Badge 1", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge1AActionPerformed

    private void btnBadge4AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge4AActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/animals4.jpg");
        if (badges[3].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 2 of the Animals Listen Up game!", "Animals Badge 4", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Animals Listen Up game to unlock it.", "Animals Badge 4", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge4AActionPerformed

    private void btnBadge5AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge5AActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/animals5.jpg");
        if (badges[4].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 1 of the Animals Odd One out game!", "Animals Badge 5", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Animals Odd One Out game to unlock it.", "Animals Badge 5", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge5AActionPerformed

    private void btnBadge6AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge6AActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/animals6.jpg");
        if (badges[5].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 2 of the Animals Odd One out game!", "Animals Badge 6", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Animals Odd One Out game to unlock it.", "Animals Badge 6", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge6AActionPerformed

    private void btnBadge2AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge2AActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/animals2.jpg");
        if (badges[1].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 2 of the Animals Mix & Match game!", "Animals Badge 6", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Animals Mix & Match game to unlock it.", "Animals Badge 6", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge2AActionPerformed

    private void btnBadge3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge3AActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/animals3.jpg");
        if (badges[2].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 1 of the Animals Listen Up game 1!", "Animals Badge 3", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Animals Listen Up game to unlock it.", "Animals Badge 3", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge3AActionPerformed

    private void btnBadge1AComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnBadge1AComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBadge1AComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //current player info is retrieved from current.dat file
        try {
            inFile = new File("./src/SaveFiles/current.dat");
            finStream = new FileInputStream(inFile);
            oinStream = new ObjectInputStream(finStream);
            current = (ArrayList<Member>) oinStream.readObject();

            for (Member r : current) {
                curPlay = r.getName();
                oinStream.close();
            }
            current.clear();
        } catch (IOException | ClassNotFoundException | NullPointerException e) {
            System.out.println(e);
        }
        curPlayer.setText(curPlay);
        //player's badgeinfo is retrieved from badgeInfo.dat file
        try {
            inFile = new File("./src/SaveFiles/badgeInfo.dat");
            finStream = new FileInputStream(inFile);
            oinStream = new ObjectInputStream(finStream);
            badgez = (ArrayList<BadgeInfo>) oinStream.readObject();

            for (BadgeInfo b : badgez) {
                if (b.getUserName().equals(curPlay)) {
                    badges[0] = b.getA1();
                    badges[1] = b.getA2();
                    badges[2] = b.getA3();
                    badges[3] = b.getA4();
                    badges[4] = b.getA5();
                    badges[5] = b.getA6();
                }
                oinStream.close();
            }

        } catch (IOException | ClassNotFoundException | NullPointerException e) {
            System.out.println(e);
        }

        ImageIcon noBadge = new ImageIcon(getClass().getResource("/Images/question-mark.jpg"));

        if (badges[0].equals("yes")) {
            ImageIcon badgeA1 = new ImageIcon(getClass().getResource("/Badges/animals1.jpg"));
            btnBadge1A.setIcon(badgeA1);
            lblBadge1A.setText("Mix & Match 1");
        } else {
            btnBadge1A.setIcon(noBadge);
            lblBadge1A.setText("<Locked>");
        }
        if (badges[1].equals("yes")) {
            ImageIcon badgeA2 = new ImageIcon(getClass().getResource("/Badges/animals2.jpg"));
            btnBadge2A.setIcon(badgeA2);
            lblBadge2A.setText("Mix & Match 2");
        } else {
            btnBadge2A.setIcon(noBadge);
            lblBadge2A.setText("<Locked>");
        }
        if (badges[2].equals("yes")) {
            ImageIcon badgeA3 = new ImageIcon(getClass().getResource("/Badges/animals3.jpg"));
            btnBadge3A.setIcon(badgeA3);
            lblBadge3A.setText("Listen Up 1");
        } else {
            btnBadge3A.setIcon(noBadge);
            lblBadge3A.setText("<Locked>");
        }
        if (badges[3].equals("yes")) {
            ImageIcon badgeA4 = new ImageIcon(getClass().getResource("/Badges/animals4.jpg"));
            btnBadge4A.setIcon(badgeA4);
            lblBadge4A.setText("Listen Up 2");
        } else {
            btnBadge4A.setIcon(noBadge);
            lblBadge5A.setText("<Locked>");
        }
        if (badges[4].equals("yes")) {
            ImageIcon badgeA5 = new ImageIcon(getClass().getResource("/Badges/animals5.jpg"));
            btnBadge5A.setIcon(badgeA5);
            lblBadge5A.setText("Odd One Out 1");
        } else {
            btnBadge5A.setIcon(noBadge);
            lblBadge5A.setText("<Locked>");
        }
        if (badges[5].equals("yes")) {
            ImageIcon badgeA6 = new ImageIcon(getClass().getResource("/Badges/animals6.jpg"));
            btnBadge6A.setIcon(badgeA6);
            lblBadge6A.setText("Odd One Out 2");
        } else {
            btnBadge6A.setIcon(noBadge);
            lblBadge6A.setText("<Locked>");
        }
    }//GEN-LAST:event_formComponentShown

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "BADGES");
        }
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "SOUND");
        }
    }//GEN-LAST:event_SoundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel ScreenLabel;
    private javax.swing.JButton Sound;
    private javax.swing.JButton btnBadge1A;
    private javax.swing.JButton btnBadge2A;
    private javax.swing.JButton btnBadge3A;
    private javax.swing.JButton btnBadge4A;
    private javax.swing.JButton btnBadge5A;
    private javax.swing.JButton btnBadge6A;
    private javax.swing.JLabel curPlayer;
    private javax.swing.JLabel jLabelAnimals;
    private javax.swing.JLabel lblBadge1A;
    private javax.swing.JLabel lblBadge2A;
    private javax.swing.JLabel lblBadge3A;
    private javax.swing.JLabel lblBadge4A;
    private javax.swing.JLabel lblBadge5A;
    private javax.swing.JLabel lblBadge6A;
    // End of variables declaration//GEN-END:variables
}
