/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrainzUp;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author x14102145
 */
public class Badges_shapes extends javax.swing.JPanel {

    private ArrayList<Member> current;
    private ArrayList<BadgeInfo> badgez;
    File inFile;
    FileInputStream finStream;
    ObjectInputStream oinStream;
    File outFile;
    FileOutputStream fStream;
    ObjectOutputStream oStream;
    String[] badges;
    String curPlay;

    /**
     * Creates new form Badges_shapes
     */
    public Badges_shapes() {
        initComponents();
        ArrayList<Member> current = new ArrayList<>();
        ArrayList<BadgeInfo> badgez = new ArrayList<>();
        badges = new String[6];
        curPlay = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBadge1S = new javax.swing.JButton();
        btnBadge2S = new javax.swing.JButton();
        btnBadge3S = new javax.swing.JButton();
        btnBadge4S = new javax.swing.JButton();
        btnBadge5S = new javax.swing.JButton();
        btnBadge6S = new javax.swing.JButton();
        lblBadge1S = new javax.swing.JLabel();
        lblBadge2S = new javax.swing.JLabel();
        lblBadge3S = new javax.swing.JLabel();
        lblBadge4S = new javax.swing.JLabel();
        lblBadge5S = new javax.swing.JLabel();
        lblBadge6S = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        ScreenLabel = new javax.swing.JLabel();
        curPlayer = new javax.swing.JLabel();
        Sound = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabelShapes = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBadge1S.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge1S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge1S.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge1S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge1SActionPerformed(evt);
            }
        });
        add(btnBadge1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 90));

        btnBadge2S.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge2S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge2S.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge2SActionPerformed(evt);
            }
        });
        add(btnBadge2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, 90));

        btnBadge3S.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge3S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge3S.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge3SActionPerformed(evt);
            }
        });
        add(btnBadge3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 120, 90));

        btnBadge4S.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge4S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge4S.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge4SActionPerformed(evt);
            }
        });
        add(btnBadge4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, 90));

        btnBadge5S.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge5S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge5S.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge5SActionPerformed(evt);
            }
        });
        add(btnBadge5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 120, 90));

        btnBadge6S.setBackground(new java.awt.Color(255, 255, 255));
        btnBadge6S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question-mark.jpg"))); // NOI18N
        btnBadge6S.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnBadge6S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadge6SActionPerformed(evt);
            }
        });
        add(btnBadge6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 120, 90));

        lblBadge1S.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge1S.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge1S.setText("<Locked>");
        lblBadge1S.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 205, 120, 20));

        lblBadge2S.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge2S.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge2S.setText("<Locked>");
        lblBadge2S.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 205, 120, 20));

        lblBadge3S.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge3S.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge3S.setText("<Locked>");
        lblBadge3S.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 205, 120, 20));

        lblBadge4S.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge4S.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge4S.setText("<Locked>");
        lblBadge4S.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 325, 120, 20));

        lblBadge5S.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge5S.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge5S.setText("<Locked>");
        lblBadge5S.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 325, 120, 20));

        lblBadge6S.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        lblBadge6S.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge6S.setText("<Locked>");
        lblBadge6S.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblBadge6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 325, 120, 20));

        Logo.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 40)); // NOI18N
        Logo.setForeground(new java.awt.Color(0, 153, 0));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setText("BrainzUp");
        add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, 40));

        ScreenLabel.setBackground(new java.awt.Color(153, 255, 255));
        ScreenLabel.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        ScreenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScreenLabel.setText("Shapes Badges");
        ScreenLabel.setOpaque(true);
        add(ScreenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 230, -1));

        curPlayer.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        curPlayer.setForeground(new java.awt.Color(0, 0, 204));
        curPlayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(curPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        Sound.setBackground(new java.awt.Color(255, 255, 255));
        Sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpg"))); // NOI18N
        Sound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sound.setContentAreaFilled(false);
        Sound.setOpaque(true);
        Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundActionPerformed(evt);
            }
        });
        add(Sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 70));

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        BackBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackBtn.setContentAreaFilled(false);
        BackBtn.setOpaque(true);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 70));

        jLabelShapes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hand_wallpaper.jpg"))); // NOI18N
        jLabelShapes.setMaximumSize(new java.awt.Dimension(530, 420));
        jLabelShapes.setMinimumSize(new java.awt.Dimension(530, 420));
        jLabelShapes.setPreferredSize(new java.awt.Dimension(530, 420));
        add(jLabelShapes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBadge6SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge6SActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/shapes6.jpg");
        if (badges[5].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 2 of the Shapes Odd One out game!", "Shapes Badge 6", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Shapes Odd One Out game to unlock it.", "Shapes Badge 6", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge6SActionPerformed

    private void btnBadge5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge5SActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/shapes5.jpg");
        if (badges[4].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 1 of the Shapes Odd One out game!", "Shapes Badge 5", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Shapes Odd One Out game to unlock it.", "Shapes Badge 5", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge5SActionPerformed

    private void btnBadge4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge4SActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/shapes4.jpg");
        if (badges[3].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 2 of the Shapes Listen Up game!", "Shapes Badge 4", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Shapes Listen Up game to unlock it.", "Shapes Badge 4", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge4SActionPerformed

    private void btnBadge3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge3SActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/shapes3.jpg");
        if (badges[2].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 1 of the Shapes Listen Up game 1!", "Shapes Badge 3", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Shapes Listen Up game to unlock it.", "Shapes Badge 3", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge3SActionPerformed

    private void btnBadge2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge2SActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/shapes2.jpg");
        if (badges[1].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 2 of the Shapes Mix & Match game!", "Shapes Badge 2", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Shapes Mix & Match game to unlock it.", "Shapes Badge 2", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge2SActionPerformed

    private void btnBadge1SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadge1SActionPerformed
        final ImageIcon icon = new ImageIcon("./src/Badges/shapes1.jpg");
        if (badges[0].equals("yes")) {
            JOptionPane.showMessageDialog(null, "Well done!!\nYou successfully finished round 1 of the Shapes Mix & Match game 1!", "Shapes Badge 1", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(null, "This badge is locked.\nPlay the Numbers Mix & Match game to unlock it.", "Shapes Badge 1", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnBadge1SActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //current player info is retrieved from current.dat file
        try {
            inFile = new File("./src/SaveFiles/current.dat");
            finStream = new FileInputStream(inFile);
            oinStream = new ObjectInputStream(finStream);
            current = (ArrayList<Member>) oinStream.readObject();

            for (Member r : current) {
                curPlay = r.getName();
                oinStream.close();
            }
            current.clear();
        } catch (IOException | ClassNotFoundException | NullPointerException e) {
            System.out.println(e);
        }
        curPlayer.setText(curPlay);
        //player's badgeinfo is retrieved from badgeInfo.dat file
        try {
            inFile = new File("./src/SaveFiles/badgeInfo.dat");
            finStream = new FileInputStream(inFile);
            oinStream = new ObjectInputStream(finStream);
            badgez = (ArrayList<BadgeInfo>) oinStream.readObject();

            for (BadgeInfo b : badgez) {
                if (b.getUserName().equals(curPlay)) {
                    badges[0] = b.getS1();
                    badges[1] = b.getS2();
                    badges[2] = b.getS3();
                    badges[3] = b.getS4();
                    badges[4] = b.getS5();
                    badges[5] = b.getS6();
                }
                oinStream.close();
            }

        } catch (IOException | ClassNotFoundException | NullPointerException e) {
            System.out.println(e);
        }

        ImageIcon noBadge = new ImageIcon(getClass().getResource("/Images/question-mark.jpg"));
        if (badges[0].equals("yes")) {
            ImageIcon badgeS1 = new ImageIcon(getClass().getResource("/Badges/shapes1.jpg"));
            btnBadge1S.setIcon(badgeS1);
            lblBadge1S.setText("Mix & Match 1");
        } else {
            btnBadge1S.setIcon(noBadge);
            lblBadge1S.setText("<Locked>");
        }
        if (badges[1].equals("yes")) {
            ImageIcon badgeS2 = new ImageIcon(getClass().getResource("/Badges/shapes2.jpg"));
            btnBadge2S.setIcon(badgeS2);
            lblBadge2S.setText("Mix & Match 2");
        } else {
            btnBadge2S.setIcon(noBadge);
            lblBadge2S.setText("<Locked>");
        }
        if (badges[2].equals("yes")) {
            ImageIcon badgeS3 = new ImageIcon(getClass().getResource("/Badges/shapes3.jpg"));
            btnBadge3S.setIcon(badgeS3);
            lblBadge3S.setText("Listen Up 1");
        } else {
            btnBadge3S.setIcon(noBadge);
            lblBadge3S.setText("<Locked>");
        }
        if (badges[3].equals("yes")) {
            ImageIcon badgeS4 = new ImageIcon(getClass().getResource("/Badges/shapes4.jpg"));
            btnBadge4S.setIcon(badgeS4);
            lblBadge4S.setText("Listen Up 2");
        } else {
            btnBadge4S.setIcon(noBadge);
            lblBadge5S.setText("<Locked>");
        }
        if (badges[4].equals("yes")) {
            ImageIcon badgeS5 = new ImageIcon(getClass().getResource("/Badges/shapes5.jpg"));
            btnBadge5S.setIcon(badgeS5);
            lblBadge5S.setText("Odd One Out 1");
        } else {
            btnBadge5S.setIcon(noBadge);
            lblBadge5S.setText("<Locked>");
        }
        if (badges[5].equals("yes")) {
            ImageIcon badgeS6 = new ImageIcon(getClass().getResource("/Badges/shapes6.jpg"));
            btnBadge6S.setIcon(badgeS6);
            lblBadge6S.setText("Odd One Out 2");
        } else {
            btnBadge6S.setIcon(noBadge);
            lblBadge6S.setText("<Locked>");
        }
    }//GEN-LAST:event_formComponentShown

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "BADGES");
        }
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "SOUND");
        }
    }//GEN-LAST:event_SoundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel ScreenLabel;
    private javax.swing.JButton Sound;
    private javax.swing.JButton btnBadge1S;
    private javax.swing.JButton btnBadge2S;
    private javax.swing.JButton btnBadge3S;
    private javax.swing.JButton btnBadge4S;
    private javax.swing.JButton btnBadge5S;
    private javax.swing.JButton btnBadge6S;
    private javax.swing.JLabel curPlayer;
    private javax.swing.JLabel jLabelShapes;
    private javax.swing.JLabel lblBadge1S;
    private javax.swing.JLabel lblBadge2S;
    private javax.swing.JLabel lblBadge3S;
    private javax.swing.JLabel lblBadge4S;
    private javax.swing.JLabel lblBadge5S;
    private javax.swing.JLabel lblBadge6S;
    // End of variables declaration//GEN-END:variables
}
