/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrainzUp;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Vali
 */
public class GUI_BrainzUp extends javax.swing.JPanel {

    private ArrayList<Member> current;
    String userName;
    File inFile;
    FileInputStream finStream;
    ObjectInputStream oinStream;
    File outFile;
    FileOutputStream fStream;
    ObjectOutputStream oStream;
    
    AUdios MC = new AUdios();
     public static int count;
    int xMouse;
    int yMouse;

    /**
     * Creates new form GUI_BrainzUp
     */
    public GUI_BrainzUp() {
        initComponents();
        try {
            inFile = new File("./src/SaveFiles/current.dat");
            finStream = new FileInputStream(inFile);
            oinStream = new ObjectInputStream(finStream);
            current = (ArrayList<Member>) oinStream.readObject();

            for (Member r : current) {
                userName = r.getName();
                oinStream.close();
            }
            current.clear();
        } catch (IOException | ClassNotFoundException | NullPointerException e) {
            System.out.println(e);
        }
        curPlayer.setText(userName);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Profile = new javax.swing.JButton();
        Watch = new javax.swing.JButton();
        Play = new javax.swing.JButton();
        Collect_Awards = new javax.swing.JButton();
        Learn = new javax.swing.JButton();
        curPlayer = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        ScreenLabel = new javax.swing.JLabel();
        PlayMouseReleasedMouseReleased = new javax.swing.JLabel();
        PauseMouseReleasedMouseReleased = new javax.swing.JLabel();
        Sound = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(530, 420));
        setMinimumSize(new java.awt.Dimension(530, 420));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile-Icon.png"))); // NOI18N
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });
        add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 100, 70));

        Watch.setBackground(new java.awt.Color(255, 255, 255));
        Watch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/watchIcon.jpeg"))); // NOI18N
        Watch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Watch.setContentAreaFilled(false);
        Watch.setOpaque(true);
        Watch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WatchActionPerformed(evt);
            }
        });
        add(Watch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 100, 100));

        Play.setBackground(new java.awt.Color(255, 255, 255));
        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gameIcon.jpeg"))); // NOI18N
        Play.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Play.setContentAreaFilled(false);
        Play.setOpaque(true);
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, 100));

        Collect_Awards.setBackground(new java.awt.Color(255, 255, 255));
        Collect_Awards.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/badgesIcon.jpeg"))); // NOI18N
        Collect_Awards.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Collect_Awards.setContentAreaFilled(false);
        Collect_Awards.setOpaque(true);
        Collect_Awards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Collect_AwardsActionPerformed(evt);
            }
        });
        add(Collect_Awards, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 100, 100));

        Learn.setBackground(new java.awt.Color(255, 255, 255));
        Learn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/learnIcon.png"))); // NOI18N
        Learn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Learn.setContentAreaFilled(false);
        Learn.setOpaque(true);
        Learn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LearnActionPerformed(evt);
            }
        });
        add(Learn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, 100));

        curPlayer.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        curPlayer.setForeground(new java.awt.Color(0, 0, 204));
        curPlayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(curPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        Logo.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 40)); // NOI18N
        Logo.setForeground(new java.awt.Color(0, 153, 0));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setText("BrainzUp");
        add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, 40));

        ScreenLabel.setBackground(new java.awt.Color(204, 102, 255));
        ScreenLabel.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        ScreenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScreenLabel.setText("Home");
        ScreenLabel.setOpaque(true);
        add(ScreenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 230, -1));

        PlayMouseReleasedMouseReleased.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sound.gif"))); // NOI18N
        PlayMouseReleasedMouseReleased.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PlayMouseReleasedMouseReleasedMouseReleased(evt);
            }
        });
        add(PlayMouseReleasedMouseReleased, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        PauseMouseReleasedMouseReleased.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Audio Off_1.png"))); // NOI18N
        PauseMouseReleasedMouseReleased.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PauseMouseReleasedMouseReleasedMouseReleased(evt);
            }
        });
        add(PauseMouseReleasedMouseReleased, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        Sound.setBackground(new java.awt.Color(255, 255, 255));
        Sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpg"))); // NOI18N
        Sound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sound.setContentAreaFilled(false);
        Sound.setOpaque(true);
        Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundActionPerformed(evt);
            }
        });
        add(Sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 70));

        ExitBtn.setBackground(new java.awt.Color(255, 255, 255));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitBtn.setContentAreaFilled(false);
        ExitBtn.setOpaque(true);
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hand_wallpaper.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(530, 420));
        jLabel1.setMinimumSize(new java.awt.Dimension(530, 420));
        jLabel1.setPreferredSize(new java.awt.Dimension(530, 420));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "LOGIN");
        }

//        InputStream in;
//        try {
//            in = new FileInputStream(new File("cartoon003.wav"));
//            AudioStream audios = new AudioStream(in);
//            AudioPlayer.player.start(audios);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//        String audioFilePath = "./src/Sounds/cartoon003.wav";
//        AudioPlayer player = new AudioPlayer();
//        player.play(audioFilePath);
    }//GEN-LAST:event_ProfileActionPerformed

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        //if current player is 'guest', system will prompt user to login/register
        if (userName.equals("guest")) {
            JOptionPane.showMessageDialog(null, "You must login or register to be able to earn badges!");
        }
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "PLAY");
        }

    }//GEN-LAST:event_PlayActionPerformed

    private void Collect_AwardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Collect_AwardsActionPerformed
        
        if (userName.equals("guest")) {
            JOptionPane.showMessageDialog(null, "Please login or register to view badge details.");
        } else {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "BADGES");
            }
        }
    }//GEN-LAST:event_Collect_AwardsActionPerformed

    private void LearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LearnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "LEARN");
        }
    }//GEN-LAST:event_LearnActionPerformed

    private void WatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WatchActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "WATCH");
        }
    }//GEN-LAST:event_WatchActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            inFile = new File("./src/SaveFiles/current.dat");
            finStream = new FileInputStream(inFile);
            oinStream = new ObjectInputStream(finStream);
            current = (ArrayList<Member>) oinStream.readObject();

            for (Member r : current) {
                userName = r.getName();
                oinStream.close();
            }
            current.clear();
        } catch (IOException | ClassNotFoundException | NullPointerException e) {
            System.out.println(e);
        }
        curPlayer.setText(userName);
    }//GEN-LAST:event_formComponentShown

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed
       
    private void SoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "SOUND");
        }
    }//GEN-LAST:event_SoundActionPerformed

    private void PauseMouseReleasedMouseReleasedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PauseMouseReleasedMouseReleasedMouseReleased
        // TODO add your handling code here:
        MC.Stop();
        PlayMouseReleasedMouseReleased.setVisible(true);
        PauseMouseReleasedMouseReleased.setVisible(false);
    }//GEN-LAST:event_PauseMouseReleasedMouseReleasedMouseReleased

    private void PlayMouseReleasedMouseReleasedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseReleasedMouseReleasedMouseReleased
        // TODO add your handling code here:
        MC.Play("C:\\Users\\Valeriu\\Downloads\\BrainzUp_App\\src\\MP3_Sund_BrainzUp\\Super+Simple+Songs+-+Animals+-+Complete+DVD+-+Animal+Songs+for+Kids.mp3");
        PlayMouseReleasedMouseReleased.setVisible(false);
        PauseMouseReleasedMouseReleased.setVisible(true);
    }//GEN-LAST:event_PlayMouseReleasedMouseReleasedMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Collect_Awards;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton Learn;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel PauseMouseReleasedMouseReleased;
    private javax.swing.JButton Play;
    private javax.swing.JLabel PlayMouseReleasedMouseReleased;
    private javax.swing.JButton Profile;
    private javax.swing.JLabel ScreenLabel;
    private javax.swing.JButton Sound;
    private javax.swing.JButton Watch;
    private javax.swing.JLabel curPlayer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
