/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrainzUp;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;

/**
 *
 * @author vanheeswijk_dennis
 */
public class Learn_GUI extends javax.swing.JPanel {

    File inFile;
    FileInputStream finStream;
    ObjectInputStream oinStream;
    ArrayList<Member> current;
    String userName;
    
    AUdios MC = new AUdios();
     public static int count;
    int xMouse;
    int yMouse;

    /**
     * Creates new form Learn_GUI
     */
    public Learn_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat = new javax.swing.JButton();
        chicken = new javax.swing.JButton();
        sheep = new javax.swing.JButton();
        chimp = new javax.swing.JButton();
        horse = new javax.swing.JButton();
        cow = new javax.swing.JButton();
        dog = new javax.swing.JButton();
        pig = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        ScreenName = new javax.swing.JLabel();
        curPlayer = new javax.swing.JLabel();
        Sound = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CatPNG.png"))); // NOI18N
        cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catActionPerformed(evt);
            }
        });
        add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 70));

        chicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Chicken.png"))); // NOI18N
        chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenActionPerformed(evt);
            }
        });
        add(chicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 110, 70));

        sheep.setBackground(new java.awt.Color(255, 255, 255));
        sheep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sheep.png"))); // NOI18N
        sheep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sheepActionPerformed(evt);
            }
        });
        add(sheep, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 110, 70));

        chimp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Chimp.png"))); // NOI18N
        chimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chimpActionPerformed(evt);
            }
        });
        add(chimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, 70));

        horse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Horse.png"))); // NOI18N
        horse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horseActionPerformed(evt);
            }
        });
        add(horse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 70));

        cow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CowPNG.png"))); // NOI18N
        cow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cowActionPerformed(evt);
            }
        });
        add(cow, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 70));

        dog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DogPNG.png"))); // NOI18N
        dog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogActionPerformed(evt);
            }
        });
        add(dog, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 110, 70));

        pig.setBackground(new java.awt.Color(255, 255, 255));
        pig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PigPNG.png"))); // NOI18N
        pig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pigActionPerformed(evt);
            }
        });
        add(pig, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 110, 70));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        Home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 70));

        Logo.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 40)); // NOI18N
        Logo.setForeground(new java.awt.Color(0, 153, 0));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setText("BrainzUp");
        add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, 40));

        ScreenName.setBackground(new java.awt.Color(255, 204, 102));
        ScreenName.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        ScreenName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScreenName.setText("Learn");
        ScreenName.setOpaque(true);
        add(ScreenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 230, -1));

        curPlayer.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        curPlayer.setForeground(new java.awt.Color(0, 0, 204));
        curPlayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(curPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        Sound.setBackground(new java.awt.Color(255, 255, 255));
        Sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpg"))); // NOI18N
        Sound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sound.setContentAreaFilled(false);
        Sound.setOpaque(true);
        Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundActionPerformed(evt);
            }
        });
        add(Sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 70));

        ExitBtn.setBackground(new java.awt.Color(255, 255, 255));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitBtn.setContentAreaFilled(false);
        ExitBtn.setOpaque(true);
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hand_wallpaper.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(530, 420));
        jLabel1.setMinimumSize(new java.awt.Dimension(530, 420));
        jLabel1.setPreferredSize(new java.awt.Dimension(530, 420));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catActionPerformed
      /*  InputStream in;
        
        try{
            in = new FileInputStream(new File("Meow.mp3"));
            AudioStream meow = new AudioStream(in);
            sun.audio.AudioPlayer.player.start(meow);
            
        }
        
        catch(Exception e){
          JOptionPane.showMessageDialog(null, e);  
        }*/
       MC.Play("C:\\Users\\Valeriu\\Desktop\\MK\\BrainzUp_App_Mark_Updates\\src\\Meow.mp3");
    }//GEN-LAST:event_catActionPerformed

    private void chickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_chickenActionPerformed

    private void sheepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sheepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sheepActionPerformed

    private void chimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chimpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chimpActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "MAIN PANEL");
        }
    }//GEN-LAST:event_HomeActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //current player info is retrieved from current.dat file
        try {
            inFile = new File("./src/SaveFiles/current.dat");
            finStream = new FileInputStream(inFile);
            oinStream = new ObjectInputStream(finStream);
            current = (ArrayList<Member>) oinStream.readObject();

            for (Member r : current) {
                userName = r.getName();
                oinStream.close();
            }
            current.clear();
        } catch (IOException | ClassNotFoundException | NullPointerException e) {
            System.out.println(e);
        }
        curPlayer.setText(userName);
    }//GEN-LAST:event_formComponentShown

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void horseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horseActionPerformed

    private void cowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cowActionPerformed
        // TODO add your handling code here:
        MC.Play("C:\\Users\\Valeriu\\Desktop\\MK\\BrainzUp_App_Mark_Updates\\src\\Moo.mp3");
    }//GEN-LAST:event_cowActionPerformed

    private void dogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogActionPerformed
        // TODO add your handling code here:
         MC.Play("C:\\Users\\Valeriu\\Desktop\\MK\\BrainzUp_App_Mark_Updates\\src\\Woof.mp3");
    }//GEN-LAST:event_dogActionPerformed

    private void pigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pigActionPerformed
        // TODO add your handling code here:
        MC.Play("C:\\Users\\Valeriu\\Desktop\\MK\\BrainzUp_App_Mark_Updates\\src\\Oink.mp3");
    }//GEN-LAST:event_pigActionPerformed

    private void SoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundActionPerformed

        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "SOUND");
        }
    }//GEN-LAST:event_SoundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel ScreenName;
    private javax.swing.JButton Sound;
    private javax.swing.JButton cat;
    private javax.swing.JButton chicken;
    private javax.swing.JButton chimp;
    private javax.swing.JButton cow;
    private javax.swing.JLabel curPlayer;
    private javax.swing.JButton dog;
    private javax.swing.JButton horse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pig;
    private javax.swing.JButton sheep;
    // End of variables declaration//GEN-END:variables
}
