/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrainzUp;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vali
 */
public class Main_GUI extends javax.swing.JFrame {
    JPanel cardsContainer;

    /**
     * Creates new form Main_GUI
     */
    public Main_GUI() {
        initComponents();
        GUI_BrainzUp up = new GUI_BrainzUp();
        BrainzUp_login log = new BrainzUp_login();
        PlayPnl play = new PlayPnl();
        Watch watch = new Watch();
        Learn_GUI learn = new Learn_GUI();
        Peppa_Youtube peppa = new Peppa_Youtube();
        BrainzUp_badges badge = new BrainzUp_badges();
        GameResult cw = new GameResult();
        GameSelect gameSelect = new GameSelect();
        Game1_Screen game1 = new Game1_Screen();
        Game2_Screen game2 = new Game2_Screen();
        Game3_Screen game3 = new Game3_Screen();
        Badges_animals badgeAnim = new Badges_animals();
        Badges_colours badgeColo = new Badges_colours();
        Badges_numbers badgeNumb = new Badges_numbers();
        Badges_shapes badgeShap = new Badges_shapes();
        MP3PlayerGU1 sound1 = new MP3PlayerGU1();
        
        cardsContainer = new JPanel(new CardLayout());
        cardsContainer.add(sound1,"SOUND");
        cardsContainer.add(up,"MAIN PANEL");
        cardsContainer.add(log,"LOGIN");
        cardsContainer.add(play,"PLAY");
        cardsContainer.add(peppa,"PEPPA");
        cardsContainer.add(learn,"LEARN");
        cardsContainer.add(badge,"BADGES");
        cardsContainer.add(watch,"WATCH");
        cardsContainer.add(gameSelect,"GAMESELECT");
        cardsContainer.add(game1,"GAME1");
        cardsContainer.add(game2,"GAME2");
        cardsContainer.add(game3,"GAME3");
        cardsContainer.add(cw,"CW");
        cardsContainer.add(badgeAnim,"BADGEANIM");
        cardsContainer.add(badgeColo,"BADGECOLO");
        cardsContainer.add(badgeNumb,"BADGENUMB");
        cardsContainer.add(badgeShap,"BADGESHAP");
          
        this.setLayout(new FlowLayout());
        this.add(cardsContainer);
        CardLayout cl = (CardLayout)(cardsContainer.getLayout());
        cl.show(cardsContainer, "MAIN PANEL");
    }

        public int subject;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BrainzUp");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(530, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
