/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrainzUp;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Valeriu
 */
public class MP3PlayerGU1 extends javax.swing.JPanel {
    
    AUdios MC = new AUdios();
    
    int xMouse;
    int yMouse;
    public static int count;
    
    int width = (Toolkit.getDefaultToolkit().getScreenSize().width / 2) - 185;
    int height = Toolkit.getDefaultToolkit().getScreenSize().height - 180;

    /**
     * Creates new form MP3PlayerGU
     */
    public MP3PlayerGU1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        selectFile = new javax.swing.JLabel();
        Pause = new javax.swing.JLabel();
        Play = new javax.swing.JLabel();
        Stop = new javax.swing.JLabel();
        Loop = new javax.swing.JLabel();
        Display = new javax.swing.JLabel();
        LoopCounter = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(255, 102, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectFileMouseReleased(evt);
            }
        });
        add(selectFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 40, 30));

        Pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PauseMouseReleased(evt);
            }
        });
        add(Pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 50, 50));

        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PlayMouseReleased(evt);
            }
        });
        add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 70, 50));

        Stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StopMouseReleased(evt);
            }
        });
        add(Stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 50, 50));

        Loop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoopMouseReleased(evt);
            }
        });
        add(Loop, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 40, 30));
        add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 350, 30));

        LoopCounter.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        LoopCounter.setText("Select");
        add(LoopCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 40, 20));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 60, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Music");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 40, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 370, 120));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 90, 50));

        Home.setBackground(new java.awt.Color(255, 153, 0));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 80, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hand_wallpaper.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -10, 580, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void PlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseReleased
        // TODO add your handling code here:
        MC.Play("C:\\Users\\Valeriu\\Downloads\\Galantis+-+No+Money+(Official+Audio).mp3");
    }//GEN-LAST:event_PlayMouseReleased

    private void PauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PauseMouseReleased
        // TODO add your handling code here:
        
        MC.Pause();
    }//GEN-LAST:event_PauseMouseReleased

    private void selectFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFileMouseReleased
        // TODO add your handling code here:
        FileFilter filter = new FileNameExtensionFilter("MP3 Files","mp3","mpeg3");
        
        JFileChooser chooser = new JFileChooser("C:\\Users\\Valeriu\\Downloads\\BrainzUp_App\\src\\MP3_Sund_BrainzUp");
        chooser.addChoosableFileFilter(filter);
        
        int returnVal = chooser.showOpenDialog(null);
        
        if ( returnVal == JFileChooser.APPROVE_OPTION)
        {
            MC.Stop();
            
            File myFile = chooser.getSelectedFile();
            String song = myFile + "";
            
            String name = chooser.getSelectedFile().getName();
            Display.setText(name);
            
            
            MC.Play(song);
        }
    }//GEN-LAST:event_selectFileMouseReleased

    private void StopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopMouseReleased
        // TODO add your handling code here:
        MC.Stop();
    }//GEN-LAST:event_StopMouseReleased

    private void LoopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoopMouseReleased
        // TODO add your handling code here:
        switch(count)
        {
            case 0:
                count = 1;
                LoopCounter.setText("Loop On");
                break;
                
            case 1:
                count = 0;
                LoopCounter.setText("Loop Off");
                //System.out.println(count);
                break;
        }
    }//GEN-LAST:event_LoopMouseReleased

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "MAIN PANEL");
        }
    }//GEN-LAST:event_HomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    public static javax.swing.JLabel Display;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Loop;
    private javax.swing.JLabel LoopCounter;
    private javax.swing.JLabel Pause;
    private javax.swing.JLabel Play;
    private javax.swing.JLabel Stop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel selectFile;
    // End of variables declaration//GEN-END:variables
}
