/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrainzUp;

import java.awt.CardLayout;

import java.awt.LayoutManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Vali
 */
public class Watch extends javax.swing.JPanel {

    private ArrayList<Member> current;
    String userName;
    File inFile;
    FileInputStream finStream;
    ObjectInputStream oinStream;
    
     AUdios MC = new AUdios();
     public static int count;
    int xMouse;
    int yMouse;

    /**
     * Creates new form GUI_BrainzUp
     */
    public Watch() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JButton();
        WatchList_lbl = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        PeppaPig = new javax.swing.JButton();
        NRhymes = new javax.swing.JButton();
        Dora = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        curPlayer = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        Sound = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 153));
        setMinimumSize(new java.awt.Dimension(600, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        Home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 70));

        WatchList_lbl.setFont(new java.awt.Font("SimSun", 1, 40)); // NOI18N
        WatchList_lbl.setForeground(new java.awt.Color(153, 0, 153));
        WatchList_lbl.setText("Watch List");
        add(WatchList_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 250, -1));
        add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 50, 50));

        PeppaPig.setBackground(new java.awt.Color(255, 255, 255));
        PeppaPig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/peppa.jpeg"))); // NOI18N
        PeppaPig.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PeppaPig.setContentAreaFilled(false);
        PeppaPig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeppaPigActionPerformed(evt);
            }
        });
        add(PeppaPig, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, 140));

        NRhymes.setBackground(new java.awt.Color(255, 255, 255));
        NRhymes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rhymes.jpeg"))); // NOI18N
        NRhymes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NRhymes.setContentAreaFilled(false);
        NRhymes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NRhymesActionPerformed(evt);
            }
        });
        add(NRhymes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 140, 140));

        Dora.setBackground(new java.awt.Color(255, 255, 255));
        Dora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dora.jpeg"))); // NOI18N
        Dora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dora.setContentAreaFilled(false);
        Dora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoraActionPerformed(evt);
            }
        });
        add(Dora, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 140, 140));

        Logo.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 40)); // NOI18N
        Logo.setForeground(new java.awt.Color(0, 153, 0));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setText("BrainzUp");
        add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, 40));

        curPlayer.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        curPlayer.setForeground(new java.awt.Color(0, 0, 204));
        curPlayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(curPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        ExitBtn.setBackground(new java.awt.Color(255, 255, 255));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitBtn.setContentAreaFilled(false);
        ExitBtn.setOpaque(true);
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 100, 50));

        Sound.setBackground(new java.awt.Color(255, 255, 255));
        Sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpg"))); // NOI18N
        Sound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sound.setContentAreaFilled(false);
        Sound.setOpaque(true);
        Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundActionPerformed(evt);
            }
        });
        add(Sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hand_wallpaper.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(530, 420));
        jLabel1.setMinimumSize(new java.awt.Dimension(530, 420));
        jLabel1.setPreferredSize(new java.awt.Dimension(530, 420));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "MAIN PANEL");
        }
    }//GEN-LAST:event_HomeActionPerformed

    private void PeppaPigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeppaPigActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "PEPPA");
        }
    }//GEN-LAST:event_PeppaPigActionPerformed

    private void NRhymesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NRhymesActionPerformed

        JOptionPane.showMessageDialog(null, "Link to nursery rhymes");
        // TODO add your handling code here:
    }//GEN-LAST:event_NRhymesActionPerformed

    private void DoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoraActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Link to view Dora videos");
    }//GEN-LAST:event_DoraActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            inFile = new File("./src/SaveFiles/current.dat");
            finStream = new FileInputStream(inFile);
            oinStream = new ObjectInputStream(finStream);
            current = (ArrayList<Member>) oinStream.readObject();

            for (Member r : current) {
                userName = r.getName();
                oinStream.close();
            }
            current.clear();
        } catch (IOException | ClassNotFoundException | NullPointerException e) {
            System.out.println(e);
        }
        curPlayer.setText(userName);
    }//GEN-LAST:event_formComponentShown
                          
    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void SoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundActionPerformed

        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "SOUND");
        }
    }//GEN-LAST:event_SoundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dora;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton NRhymes;
    private javax.swing.JButton PeppaPig;
    private javax.swing.JButton Sound;
    private javax.swing.JLabel WatchList_lbl;
    private javax.swing.JLabel curPlayer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
